In [10]:
import pandas as pd
import numpy as np
import csv
import time, operator
import os
import sys
from string import maketrans

# coding: utf8
from __future__ import print_function
import os, urllib, json, shutil, sys, time, csv, re, codecs, unicodedata, glob
from nltk.corpus import stopwords
import pandas as pd
from nltk.stem.snowball import FrenchStemmer
from datetime import datetime
from string import maketrans
from ner.predict import entities
from pprint import pprint

In [26]:
df = pd.DataFrame({},columns = ['phrase','context','intent'])
df

Empty DataFrame
Columns: [phrase, context, intent]
Index: []

In [27]:
df2 = pd.DataFrame({1,2,3},columns = ['phrase','context','intent'])
df2

PandasError: DataFrame constructor not properly called!

In [8]:
df = df.append([6,7,8])

In [30]:
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [31]:
data = pd.DataFrame({"A": range(3)})
data

A
0  0
1  1
2  2

In [32]:
df.append(data)

A
0  0
1  1
2  2

In [33]:
df = df = pd.DataFrame({},columns = ['phrase','context','intent'])

In [57]:
d = {'one' : pd.Series([1., 2., 3.], index=['a', 'b', 'c']),'two' : pd.Series([1., 2., 3., 4.], index=['a', 'b', 'c', 'd'])}

In [58]:
df = pd.DataFrame(d,columns=['si','r',])
df

Empty DataFrame
Columns: [si, r]
Index: []

In [59]:
data2 = [{'a': 1, 'b': 2}, {'a': 5, 'b': 10, 'c': 20}]

In [65]:
df = pd.DataFrame(data2)
df

a   b   c
0  1   2 NaN
1  5  10  20

In [66]:
df=df.append({'a':90},ignore_index=True)

In [67]:
df

a   b   c
0   1   2 NaN
1   5  10  20
2  90 NaN NaN

In [81]:
df = pd.DataFrame({},columns = ['phrase','context','intent'])
df

Empty DataFrame
Columns: [phrase, context, intent]
Index: []

In [88]:
df=df.append({'phrase':90},ignore_index=True)

In [89]:
df

phrase  context  intent
0      90      NaN     NaN
1      90      NaN     NaN
2      90      NaN     NaN

In [76]:
a = input('go')

gofzf


In [77]:
a

'fzf'

In [78]:
df

phrase  context  intent
0      90      NaN     NaN

In [80]:
df.size

3

In [85]:
df.tail(2)

phrase  context  intent
0      90      NaN     NaN

In [91]:
df.ix[:-1]

Empty DataFrame
Columns: [phrase, context, intent]
Index: []

In [92]:
df

phrase  context  intent
0      90      NaN     NaN
1      90      NaN     NaN
2      90      NaN     NaN

In [93]:
del df.ix[:-1]

AttributeError: __delitem__

In [94]:
df

phrase  context  intent
0      90      NaN     NaN
1      90      NaN     NaN
2      90      NaN     NaN

In [98]:
df.iloc[-1,]

phrase     90
context   NaN
intent    NaN
Name: 2, dtype: float64

In [101]:
df.drop(df.index[len(df)-1])


phrase  context  intent
0      90      NaN     NaN
1      90      NaN     NaN

In [12]:


word_label=False
with open('./data/inputs/sentences.txt', 'w+') as sentences:
    with open('./data/inputs/labels.txt', 'w+') as labels:
        with open('./treevertical/data/dataformated.csv', 'rb') as f:
            
            
            reader = csv.DictReader(f, fieldnames=['label', 'sentence'], delimiter=';')
            if word_label == True:
                label_index = self.label_indexing()
            i = 0
            for row in reader:
                if row['sentence']=='' or row['label']=='':
                    pass
                else:
                    if i == 0:
                        i += 1
                    else:
                        txt = parse(row['sentence'])
                        if word_label == True:
                            label = label_index[row['label']]
                        else:
                            label = row['label']
                        sentences.write(txt+'\n')
                        labels.write(str(label)+'\n')
#print('number of classes:', self.get_number_of_classes())
print('classes names:')
target_names = self.get_classes_names()  # here we save classes into the json
pprint(target_names)
print('...csv preprocessing ended')

NameError: name 'self' is not defined

In [20]:


word_label=False
with open('./data/inputs/sentences.txt', 'w+') as sentences:
    with open('./data/inputs/labels.txt', 'w+') as labels:
        with open('./treevertical/data/dataformated.csv', 'rb') as f:
            reader = pd.read_csv('./treevertical/data/dataformated.csv', sep=';')
            
            if word_label == True:
                label_index = self.label_indexing()
            i = 0
            for index,row in reader.iterrows():
                print (row)
                print(type(row))
                if row['sentence']=='' or row['label']=='':
                    pass
                else:
                    if i == 0:
                        i += 1
                    else:
                        txt = parse(row['sentence'])
                        if word_label == True:
                            label = label_index[row['label']]
                        else:
                            label = row['label']
                        sentences.write(txt+'\n')
                        labels.write(str(label)+'\n')
#print('number of classes:', self.get_number_of_classes())
print('classes names:')
target_names = self.get_classes_names()  # here we save classes into the json
pprint(target_names)
print('...csv preprocessing ended')

sentence    Je suis ejejejejej
label                        1
Name: 0, dtype: object
<class 'pandas.core.series.Series'>
sentence    eheheheheh
label                1
Name: 1, dtype: object
<class 'pandas.core.series.Series'>
sentence    zhzhzhzhzhzhz
label                   1
Name: 2, dtype: object
<class 'pandas.core.series.Series'>
sentence    ezezezezeze
label                 0
Name: 3, dtype: object
<class 'pandas.core.series.Series'>
sentence    ezezze
label            0
Name: 4, dtype: object
<class 'pandas.core.series.Series'>
sentence    trhthrthrt
label                1
Name: 5, dtype: object
<class 'pandas.core.series.Series'>
sentence    thrhrhrhrh
label                1
Name: 6, dtype: object
<class 'pandas.core.series.Series'>
sentence    rjrjrjrjrjrjrjrj
label                      1
Name: 7, dtype: object
<class 'pandas.core.series.Series'>
classes names:


NameError: name 'self' is not defined

In [11]:
def parse(txt):
    """ We create the dictionary from the labeled data """
    # Input : Liste de 2-uple contenant (mail,label)
    # 0utput : Dictionnaire = liste de 2-uple avec l'ensemble des mots de tous les mails (mot,count)

    not_letters_or_digits =u'!"#%\'()*+,-./:;<=>?@[\]^_`{|}~1234567890'
    empty = u' '*len(not_letters_or_digits)
    trantab = maketrans(not_letters_or_digits, empty)
    stemmer = FrenchStemmer()

    a = txt.lower() # On met tout en minuscule
    a = a.replace('\n',' ') # On enleve les retours à la ligne
    a = a.replace('\r',' ') # On enleve les retours à la ligne
    a = a.translate(trantab) # On enleve la ponctuation
    a = a.decode('utf-8', 'replace')
    a = a.split() # On répartit selon les espaces
    #a = [stemmer.stem(word) for word in a]

    a = [word for word in a if not word.isdigit()]
    stop = stopwords.words('french')
    a = [word for word in a if not (word in stop)]  # On enleve les stopwords
    a = ' '.join(a)
    a = a.encode('utf-8', 'ignore')
    a = unicodedata.normalize('NFKD', unicode(a, 'utf-8')).encode('ASCII', 'ignore') # On enleve les accents et caractères speciaux
    a = ' '.join([word.strip(' \t\n\r') for word in a.split()])

    return a

In [35]:
test = np.array([1,2,3,2,1,2,3])
test.shape

(7,)

In [33]:
np.logical_or.reduce(test[:] == 1)

True

In [38]:
test[test[:, ] == 1]

array([1, 1])

In [54]:
selec = np.random.choice(9,4,replace=False)
selec

array([0, 6, 5, 1])

In [55]:
a=np.array([0,1,2,3,4,5,6,7,8,9])
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
import random

In [64]:
ech =random.sample(range(0,5),4)
ech

[2, 1, 0, 3]